---
title: "Topic modeling"
author: "Dmitriy Selivanov"
date: "`r Sys.Date()`"
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, echo=TRUE, warning=FALSE, message=FALSE)
set.seed(2016L)
```


# Latent Semantic Analysis

# Latent Dirichlet Allocation

```{r}
library(text2vec)
data("movie_review")
tokens = movie_review$review %>% 
  tolower %>% 
  word_tokenizer
# turn off progressbar because it won't look nice in rmd
it = itoken(tokens, ids = movie_review$id, progressbar = FALSE)
v = create_vocabulary(it) %>% 
  prune_vocabulary(term_count_min = 10, doc_proportion_max = 0.2)
vectorizer = vocab_vectorizer(v)
dtm = create_dtm(it, vectorizer, type = "lda_c")

lda_model = LDA$new(n_topics = 10, 
                    vocabulary = v, 
                    doc_topic_prior = 0.1, 
                    topic_word_prior = 0.01)
doc_topic_distr = lda_model$fit_transform(dtm, n_iter = 100, 
                                          convergence_tol = 0.01, 
                                          check_convergence_every_n = 10)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
lda_model$plot(out.dir = "./topic_modeling_files/ldavis", lambda.step = 0.1, open.browser = FALSE)
```
```{r, eval=FALSE}
lda_model$plot()
```

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>LDAvis</title>
  <script src="topic_modeling_files/ldavis/d3.v3.js"></script>
  <script src="topic_modeling_files/ldavis/ldavis.js"></script>
  <link rel="stylesheet" type="text/css" href="topic_modeling_files/ldavis/lda.css">
</head>

<body>
  <div id = "lda"></div>
  <script>
    var vis = new LDAvis("#lda", "topic_modeling_files/ldavis/lda.json");
  </script>
</body>
